import { IoMdAdd } from 'react-icons/io'
import { FaMinus } from 'react-icons/fa'
import { useEffect, useState } from 'react'
import { onboard } from '../utils/onboard'
// import contract from '../contracts/PakoNFT.json'
// import { ethers } from 'ethers'
import Head from 'next/head'
import {
  getBlockchainData,
  isPausedState,
  isPreSaleState,
  isPublicSaleState,
  preSaleMintFunc,
} from '../utils/interact'
import Web3 from 'web3'

// console.log(wallets)
let web3 = new Web3(Web3.givenProvider)

const MintPage = () => {
  const [walletAddress, setWalletAddress] = useState(null)
  const [mintAmount, setMintAmount] = useState(1)
  const [countMinted, setCountMinted] = useState(0)
  const [supply, setSupply] = useState('100')
  const [isPaused, setPaused] = useState()
  const [isPreSale, setPreSale] = useState(false)
  const [isPublic, setPublic] = useState(false)
  const [loading, setLoading] = useState(false)
  const [status, setStatus] = useState(null)
  const [switchStatus, setSwitch] = useState(false)

  useEffect(() => {
    const init = async () => {
      const chain = await web3.eth.getChainId()
      if (chain === 4) {
        setPreSale(await isPreSaleState())
        setPaused(await isPausedState())
        setPublic(await isPublicSaleState())
      } else {
        setSwitch(true)
      }
    }
    init()
  }, [])

  const connectWalletHandler = async () => {
    const chain = await web3.eth.getChainId()
    if (chain === 4) {
      setSwitch(false)
      const wallets = await onboard.connectWallet()
      if (wallets[0]) {
        setWalletAddress(wallets[0].accounts[0].address)
        let { totalSupply, maxSupply } = await getBlockchainData()
        setCountMinted(totalSupply)
        setSupply(maxSupply)
        console.log(totalSupply)
      }
    } else {
      setSwitch(true)
    }
    // console.log(wallets[0])
  }

  const switchHandler = async (network) => {
    try {
      await window.ethereum.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: '0x4' }],
      })
      // location.reload()
      setSwitch(false)
    } catch (switchError) {
      // This error code indicates that the chain has not been added to MetaMask.
      if (switchError.code === 4902) {
        try {
          await window.ethereum.request({
            method: 'wallet_addEthereumChain',
            params: [
              {
                chainId: network.chainId,
                rpcUrls: network.rpcUrls,
                chainName: network.chainName,
                nativeCurrency: network.nativeCurrency,
                blockExplorerUrls: network.blockExplorerUrls,
              },
            ],
          })
          // setChainIdMsg(null)
        } catch (addError) {
          alert('Error occurred')
        }
      } else {
        throw switchError
      }
    }
  }

  const handleAdd = () => {
    if (mintAmount < 3) {
      setMintAmount(++mintAmount)
    }
  }

  const handleMinus = () => {
    if (mintAmount > 1) {
      setMintAmount(--mintAmount)
    }
  }

  const MintingHandler = async () => {
    const chain = await web3.eth.getChainId()
    if (chain === 4) {
      setSwitch(false)
      if (!isPaused) {
        setLoading(true)
        let { status, success } = await preSaleMintFunc(
          walletAddress,
          mintAmount,
        )
        setStatus({ success, status })
        setLoading(false)
        let { totalSupply } = await getBlockchainData()
        setCountMinted(totalSupply)
      } else {
        alert('Minting Paused')
      }
    } else {
      setSwitch(true)
    }
  }

  return (
    <div className="mintContainer h-full w-full min-h-screen">
      <Head>
        <title>Minting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mintSection h-full w-full min-h-screen flex flex-col items-center justify-center">
        <div className="bgImg">
          <img
            src="https://wallpaperaccess.com/full/5361112.jpg"
            className="bgImgae animate-pulse"
            alt="..."
          />
        </div>
        <div className="mintCard  flex flex-col items-center justify-center mx-auto w-90">
          {switchStatus ? (
            <div className="switchContent">
              <p className="text-brand-white">
                Please Switch your network to Rinkeby Testnet
              </p>
              <button
                onClick={switchHandler}
                className="font-coiny mt-5 mb-5 uppercase w-full p-2 bg-brand-pink rounded-lg bg-gradient-to-br from-brand-purple to-brand-pink shadow-lg text-2xl text-brand-white hover:shadow-pink-400/50"
              >
                Switch
              </button>
            </div>
          ) : null}
          <h2 className="font-coiny font-bold uppercase text-brand-purple text-3xl">
            {isPaused ? 'Paused' : isPreSale ? 'Pre - Sale' : 'Public'}
          </h2>
          <p className="space-x-4 mt-5 text-brand-white text-sm p-2 shadow-sm shadow-brand-pink rounded-lg">
            {walletAddress !== null ? walletAddress : ''}
          </p>
          <div className="flex items-center flex-wrap justify-center mt-3">
            <div className="relative  mt-5">
              <div className="countBox font-coiny">
                <span className="text-brand-purple ">{countMinted}</span> |{' '}
                {supply}
              </div>
              <img
                className=" w-full rounded-lg h-72"
                src="https://img-s1.onedio.com/id-624ead38e37476c216b2ac6b/rev-0/w-620/f-jpg/s-ff1cf6479409c5b23a919be96e6ec3ce731faa7c.jpg"
              />
            </div>
            <div className="flex flex-col items-center w-80 m-5 counterDIv">
              <div className="flex items-center w-full justify-between">
                <button
                  className="bg-[#f0e9e9] p-2 font-bold rounded-lg outline-none"
                  onClick={handleMinus}
                >
                  <FaMinus className="font-bold text-2xl" />
                </button>
                <p className="font-coiny text-brand-purple text-2xl font-bold">
                  {mintAmount}
                </p>
                <button
                  className="bg-[#f0e9e9] p-2 font-bold rounded-lg"
                  onClick={handleAdd}
                >
                  <IoMdAdd className="font-bold text-2xl" />
                </button>
              </div>
              <p className="text-md text-brand-white font-coiny mt-5">
                Max Mint Amount: 3
              </p>
              <div className="totalPrice flex items-center font-coiny w-full py-3 mt-5 text-md border-x-0 border-y-brand-yellow border-2">
                <h3 className="w-1/3 text-brand-yellow text-xl">Total</h3>
                <div className="prices flex items-center w-2/3">
                  <p className="text-brand-yellow mx-5">
                    {0.01 * mintAmount} ETH{' '}
                  </p>
                  <p className="text-brand-white"> + Gas Fee</p>
                </div>
              </div>
              {walletAddress ? (
                <button
                  disabled={loading}
                  className="font-coiny mt-10 uppercase w-full p-4 bg-brand-pink rounded-lg bg-gradient-to-br from-brand-purple to-brand-pink shadow-lg text-2xl text-brand-white hover:shadow-pink-400/50  hover:animate-pulse"
                  onClick={MintingHandler}
                >
                  {loading ? 'Loading...' : 'Mint'}
                </button>
              ) : (
                <button
                  className="font-coiny mt-10 uppercase w-full p-4 bg-brand-pink rounded-lg bg-gradient-to-br from-brand-purple to-brand-pink shadow-lg text-2xl text-brand-white hover:shadow-pink-400/50  hover:animate-pulse"
                  onClick={connectWalletHandler}
                >
                  Connect Wallet
                </button>
              )}
            </div>
          </div>
          {/* status  */}
          {status ? (
            <div
              className={`rounded-lg text-start h-full border ${
                status.success ? 'border-brand-green' : 'border-brand-pink'
              } w-full p-4 mt-4`}
            >
              <p className="flex flex-col space-y-2 text-brand-white text-sm break-words">
                {status.status}
              </p>
            </div>
          ) : null}
          {/* contract  */}
          <div className="flex flex-col items-center mt-6 ">
            <h1 className="font-coiny text-3xl font-bold text-brand-pink">
              Contract address
            </h1>
            <p className="text-brand-white mt-2 text-sm">
              0x94FC1035713F7a2DAae589EA3F7a4494650240f7
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default MintPage
